services:
  nginx-router:
    build: .
    image: nginx-router:latest
    container_name: nginx-router
    network_mode: host
    environment:
      CERTBOT_EMAIL: ${CERTBOT_EMAIL:-}
      USE_STAGING: ${USE_STAGING:-0}
      USE_CERTBOT: ${USE_CERTBOT:-1}
    volumes:
      - ./sites-available:/etc/nginx/sites-available:ro
      - ./letsencrypt:/etc/letsencrypt
      - ./logs:/var/log/nginx
