services:
  nginx-router:
    build: .
    image: nginx-router:latest
    container_name: nginx-router
    network_mode: host
    env_file:
      - path: .env
        required: false
    volumes:
      - ./sites-available:/etc/nginx/sites-available:ro
      - ./letsencrypt:/etc/letsencrypt
      - ./logs:/var/log/nginx
